name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make deps
      - run: make test
      - run: make test-only-on-ubuntu
      - run: make test-install

  wolfi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wolfi-dev/wolfi-act@main
        with:
          packages: build-base,apk-tools
          command: make deps && make test && make test-only-on-chainguard && make test-install
