name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: wolfi-dev/wolfi-act@main
        with:
          packages: build-base,bash,erlang,gfortran,go,default-jdk,nodejs,perl,php,python3,ruby,rust
          run: make test
